config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'home#index'
  get '/about', to: 'home#about', as: :about
  get '/contact', to: 'home#contact', as: :contact
  resources :projects
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @projects = Project.all
  end

  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :project_link, :website_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/about.html.erb
<h1>About this web site</h1>
<h3>How to use this web site:</h3>
<p>1. Sign Up account if you do not have an account</p>
<p>2. Sign In your account</p>
<p>3. Create new project through "New Project" link</p>
<p>4. Project can be showed, edited, deleted project</p>

app/views/home/contact.html.erb
<h1>Contact</h1>
<p>This is contact page</p>

app/views/home/index.html.erb
<h1>All Projects</h1>

<br>
<%= render partial: 'projects/summary', collection: @projects, as: :project %>

<%= link_to('New Project', new_project_path) if current_admin %>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_footer.html.erb
<footer class="footer"></footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default">
    <ul class="nav navbar-nav">
      <li class="nav-item nav link"><%= link_to 'Home', root_path %></li>
      <li class="nav-item nav link"><%= link_to 'About', about_path %></li>
      <li class="nav-item nav link"><%= link_to 'Contact', contact_path %></li>
    </ul>
    <ul id="navRight" class="nav navbar-nav navbar-right">
      <li class="nav-item nav link"><%= link_to 'Sign Up', new_admin_registration_path %></li>
      <li class="nav-item nav link"><%= link_to 'Sign In', new_admin_session_path %></li>
      <li class="nav-item nav link"><%= link_to 'Sign Out', destroy_admin_session_path, :method => :delete %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row">
    <%= f.label :title, class: "col-sm-4 form-control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :description, class: "col-sm-4 form-control-label" %>
    <div class="col-sm-8">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :project_link, class: "col-sm-4 form-control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :project_link, class: "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :website_link, class: "col-sm-4 form-control-label" %>
    <div class="col-sm-8">
      <%= f.text_field :website_link, class: "form-control" %>
    </div>
  </div>
  <div class="actions" id="newPeojectBtn">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<table class="table table-responsive project">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Project Link</th>
      <th>Website Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= project.title %></td>
      <td><%= project.description %></td>
      <td><%= project.project_link %></td>
      <td><%= project.website_link %></td>
      <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
</table>

app/views/projects/_summary.html.erb
<table class="project-summary table table-responsive">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Project Link</th>
      <th>Website Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= project.title %></td>
      <td><%= project.description %></td>
      <td><%= project.project_link %></td>
      <td><%= project.website_link %></td>
      <td><%= link_to 'Show', project %></td>
      <% if current_admin %>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/projects/edit.html.erb
<div class="col-xs-12">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-xs-8 col-sm-offset-1">
      <h1>Editing Project</h1>
    </div>
  </div>
  <div class="row">
    <section class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-xs-8 col-sm-offset-1 well">
      <div class="row col-xs-8 col-xs-offset-1">
        <%= render 'form' %></div>
        <div class="row col-xs-12">
          <%= link_to 'Show', @project %> |
          <%= link_to 'Back', projects_path %>
        </div>
      </section>
    </div>
  </div>

app/views/projects/index.html.erb
<h1>Listing Projects</h1>

<br>
<%= render @projects %>

<%= link_to('New Project', new_project_path) if current_admin %>

app/views/projects/new.html.erb
<div class="col-xs-12">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-xs-8 col-sm-offset-1">
      <h1>New Project</h1>
    </div>
  </div>
  <div class="row">
    <section class="col-lg-8 col-lg-offset-1 col-md-8 col-md-offset-1 col-xs-8 col-sm-offset-1 well">
      <div class="row col-xs-8 col-xs-offset-1">
        <%= render 'form' %>
      </div>
      <div class="row col-xs-12">
        <br><%= link_to 'Back', projects_path %>
      </div>
    </section>
  </div>
</div>

app/views/projects/show.html.erb
<h1>Showing Project</h1>
<table class="table table-responsive">
  <tbody>
    <tr>
      <th><strong>Title:</strong></th>
      <td><%= @project.title %></td>
    </tr>
    <tr>
      <th><strong>Description:</strong></th>
      <td><%= @project.description %></td>
    </tr>
    <tr>
      <th><strong>Project link:</strong></th>
      <td><%= @project.project_link %></td>
    </tr>
    <tr>
      <th><strong>Website link:</strong></th>
      <td><%= @project.website_link %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>